### ISSUE TITLE
How did you deploy this fully accessible static site on GitHub Pages?

### ISSUE THREAD

**Issue by 5ervant** [contentful/gallery-app-react#7]
Look at my GitHub Pages-deployed static site: https://expo-gh-pages.github.io
If you directly visit https://expo-gh-pages.github.io/Links it will show you a _"Page not found"_.

However, if you directly visit your https://contentful.github.io/gallery-app-react/gallery/54O5P32wmcY0wiAY0ewA2e it's not showing a _"Page not found"_.

May I know where can I locate that static page's file on this repository?
And how did you deploy that site on GitHub Pages?
**Many thanks !!**

**Comment by Khaledgarbaya** [comment]
you can check the bundled app [here](https://github.com/contentful/gallery-app-react/tree/gh-pages) the trick here is to create another 404.html file that has the same content as your index.html page so when GitHub does not find the page it fallbacks to that one

**Comment by 5ervant** [comment]
@Khaledgarbaya Yes, I located your bundle app and cloned my _"index.html"_ as _"404.html"_ a hour ago: https://github.com/expo-gh-pages/expo-gh-pages.github.io/blob/master/404.html

I wonder if that's the community standard approach or this one https://github.com/rafrex/spa-github-pages or else..

**Comment by Khaledgarbaya** [comment]
I think there are different ways to work around that I find the 404 trick easier
