### ISSUE TITLE
Is this repo still accepting PR's ?

### ISSUE THREAD

**Issue by gabrielreisn** [contentful/gallery-app-react#8]
@Khaledgarbaya @stefanjudis I'd noticed a lot a room for improvement like migrating the application to the latest react version (including hooks) with a major upgrade. Are you both still maintaining the application? Can I proceed with the changes? I'd love to contribute to the project!

**Comment by stefanjudis** [comment]
I'm not with Contentful anymore so I'd say it's up to @Khaledgarbaya :)

**Comment by Khaledgarbaya** [comment]
@gabrielreisn sure thing

**Comment by phoebeschmidt** [comment]
Hey @gabrielreisn! Thanks so much for your interest in assisting with this example app. Unfortunately `gallery-app-react` isn't high priority for maintenance on our side (we have lots of other open source tools that keep us busy :) ) That said we would absolutely welcome your contributions! Go ahead and make PRs and we will get around to them when we can. (And feel free to @ mention me here)
